import type { IconAliases } from 'vuetify'
import type { Component, PropType } from 'vue'
import { defineComponent, h } from 'vue'
import {
  AlertCircle,
  AlertTriangle,
  ArrowDown,
  ArrowRight,
  ArrowUp,
  ArrowUpRight,
  Award,
  Bell,
  BookOpen,
  BookUser,
  Briefcase,
  Calendar,
  Check,
  CheckCircle,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsLeft,
  ChevronsRight,
  Circle,
  CircleHelp,
  Clock,
  CloudSun,
  Compass,
  Contact,
  Copyright,
  Ellipsis,
  ExternalLink,
  Eye,
  EyeOff,
  FileText,
  FolderGit2,
  Github,
  Globe,
  GraduationCap,
  GripVertical,
  Heading,
  Image,
  Inbox,
  Info,
  Instagram,
  Key,
  Landmark,
  Layers,
  Layout,
  LayoutDashboard,
  LayoutGrid,
  Lightbulb,
  ListChecks,
  ListOrdered,
  Lock,
  LockKeyhole,
  LogOut,
  Mail,
  MailOpen,
  Menu,
  MessageCircleQuestion,
  MessageSquare,
  Minus,
  Moon,
  MousePointerClick,
  PanelBottom,
  PanelTop,
  Palette,
  Paperclip,
  Pencil,
  Plus,
  RefreshCw,
  Reply,
  Save,
  Search,
  Settings,
  Shield,
  ShieldCheck,
  ShoppingBag,
  Signal,
  Smartphone,
  Sparkles,
  Star,
  StarHalf,
  Sun,
  Tag,
  Trash2,
  TrendingUp,
  Type,
  UnfoldVertical,
  Upload,
  User,
  UserCog,
  UserRound,
  Users,
  X,
  XCircle,
  Zap,
} from 'lucide-vue-next'

import checkboxChecked from '@/assets/svg/checkbox-checked.svg'
import checkboxIndeterminate from '@/assets/svg/checkbox-indeterminate.svg'
import checkboxUnchecked from '@/assets/svg/checkbox-unchecked.svg'
import radioChecked from '@/assets/svg/radio-checked.svg'
import radioUnchecked from '@/assets/svg/radio-unchecked.svg'

// Vuetify's own checkbox/radio aliases still resolve to these mdi names
const customIcons: Record<string, unknown> = {
  'mdi-checkbox-blank-outline': checkboxUnchecked,
  'mdi-checkbox-marked': checkboxChecked,
  'mdi-minus-box': checkboxIndeterminate,
  'mdi-radiobox-marked': radioChecked,
  'mdi-radiobox-blank': radioUnchecked,
}

// The same icon library as the public website (lucide-vue-next), addressed by kebab-case name,
// e.g. <VIcon icon="mail" />. Add an entry here before using a new name.
const lucideIcons: Record<string, Component> = {
  'alert-circle': AlertCircle,
  'alert-triangle': AlertTriangle,
  'arrow-down': ArrowDown,
  'arrow-right': ArrowRight,
  'arrow-up': ArrowUp,
  'arrow-up-right': ArrowUpRight,
  'award': Award,
  'bell': Bell,
  'book-open': BookOpen,
  'book-user': BookUser,
  'briefcase': Briefcase,
  'calendar': Calendar,
  'check': Check,
  'check-circle': CheckCircle,
  'check-circle-2': CheckCircle2,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevron-up': ChevronUp,
  'chevrons-left': ChevronsLeft,
  'chevrons-right': ChevronsRight,
  'circle': Circle,
  'circle-help': CircleHelp,
  'clock': Clock,
  'cloud-sun': CloudSun,
  'compass': Compass,
  'contact': Contact,
  'copyright': Copyright,
  'ellipsis': Ellipsis,
  'external-link': ExternalLink,
  'eye': Eye,
  'eye-off': EyeOff,
  'file-text': FileText,
  'folder-git-2': FolderGit2,
  'github': Github,
  'globe': Globe,
  'graduation-cap': GraduationCap,
  'grip-vertical': GripVertical,
  'heading': Heading,
  'image': Image,
  'inbox': Inbox,
  'info': Info,
  'instagram': Instagram,
  'key': Key,
  'landmark': Landmark,
  'layers': Layers,
  'layout': Layout,
  'layout-dashboard': LayoutDashboard,
  'layout-grid': LayoutGrid,
  'lightbulb': Lightbulb,
  'list-checks': ListChecks,
  'list-ordered': ListOrdered,
  'lock': Lock,
  'lock-keyhole': LockKeyhole,
  'log-out': LogOut,
  'mail': Mail,
  'mail-open': MailOpen,
  'menu': Menu,
  'message-circle-question': MessageCircleQuestion,
  'message-square': MessageSquare,
  'minus': Minus,
  'moon': Moon,
  'mouse-pointer-click': MousePointerClick,
  'palette': Palette,
  'panel-bottom': PanelBottom,
  'panel-top': PanelTop,
  'paperclip': Paperclip,
  'pencil': Pencil,
  'plus': Plus,
  'refresh-cw': RefreshCw,
  'reply': Reply,
  'save': Save,
  'search': Search,
  'settings': Settings,
  'shield': Shield,
  'shield-check': ShieldCheck,
  'shopping-bag': ShoppingBag,
  'signal': Signal,
  'smartphone': Smartphone,
  'sparkles': Sparkles,
  'star': Star,
  'star-half': StarHalf,
  'sun': Sun,
  'tag': Tag,
  'trash-2': Trash2,
  'trending-up': TrendingUp,
  'type': Type,
  'unfold-vertical': UnfoldVertical,
  'upload': Upload,
  'user': User,
  'user-cog': UserCog,
  'user-round': UserRound,
  'users': Users,
  'x': X,
  'x-circle': XCircle,
  'zap': Zap,
}

// "<name>-filled" renders the solid variant, e.g. "star-filled" for a full rating star
const FILLED_SUFFIX = '-filled'

const warnedNames = new Set<string>()

const resolveLucide = (name: string) => {
  const isFilled = name.endsWith(FILLED_SUFFIX)
  const component = lucideIcons[isFilled ? name.slice(0, -FILLED_SUFFIX.length) : name]

  if (!component && import.meta.env.DEV && !warnedNames.has(name)) {
    warnedNames.add(name)
    console.warn(`[icons] "${name}" is not registered in src/plugins/vuetify/icons.ts`)
  }

  return { component, isFilled }
}

const LucideIcon = defineComponent({
  name: 'LucideIcon',
  inheritAttrs: false,
  props: {
    icon: { type: [String, Object, Function, Array] as PropType<unknown>, default: undefined },
    tag: { type: String, required: true },
  },
  setup(props, { attrs }) {
    return () => {
      const name = typeof props.icon === 'string' ? props.icon : ''

      if (customIcons[name])
        return h(props.tag, attrs, [h(customIcons[name] as Component)])

      const { component, isFilled } = resolveLucide(name)

      return h(props.tag, attrs, component
        ? [h(component, {
          'class': 'lucide-icon',
          'stroke-width': 1.75,
          'fill': isFilled ? 'currentColor' : 'none',
          'aria-hidden': 'true',
        })]
        : [])
    }
  },
})

const aliases: Partial<IconAliases> = {
  info: 'info',
  success: 'check-circle-2',
  warning: 'alert-triangle',
  error: 'alert-circle',
  calendar: 'calendar',
  collapse: 'chevron-up',
  complete: 'check',
  cancel: 'x',
  close: 'x',
  delete: 'x-circle',
  clear: 'x',
  prev: 'chevron-left',
  next: 'chevron-right',
  delimiter: 'circle',
  sort: 'arrow-up',
  expand: 'chevron-down',
  menu: 'menu',
  subgroup: 'chevron-down',
  dropdown: 'chevron-down',
  edit: 'pencil',
  ratingEmpty: 'star',
  ratingFull: 'star-filled',
  ratingHalf: 'star-half',
  loading: 'refresh-cw',
  first: 'chevrons-left',
  last: 'chevrons-right',
  unfold: 'unfold-vertical',
  file: 'paperclip',
  plus: 'plus',
  minus: 'minus',
  sortAsc: 'arrow-up',
  sortDesc: 'arrow-down',
  contacts: 'book-user',
  institution: 'landmark',
  education: 'graduation-cap',
  country: 'globe',
  level: 'signal',
}

export const icons = {
  defaultSet: 'lucide',
  aliases,
  sets: {
    lucide: { component: LucideIcon },
  },
}
